config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get '/post/tag/:name', to:"posts#tag"
  resources :users, only: [:edit, :update, :show] do
    get 'show_following'
    get 'show_follower'
    get 'show_article'
    get 'show_comment'
    get 'show_good'
    get 'show_question'
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    collection do
      get 'search'
    end
    resources :goods, only: [:create, :destroy]
    resources :bads, only: [:create, :destroy]
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :comgoods, only: [:create, :destroy]
      resources :combads, only: [:create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :comgoods, dependent: :destroy
  has_many :comgood_users, through: :comgoods, source: :user
  has_many :combads, dependent: :destroy
  has_many :combad_users, through: :combads, source: :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_tag, only: [:new, :create, :edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create(comment_params)
    if comment.save
      redirect_to "/posts/#{comment.post_id}", notice: 'コメントを投稿しました。'
    else
      redirect_to "/posts/#{comment.post_id}", alert: 'コメントの投稿に失敗しました。'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
  end

  def update
    @comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
    if @comment.update(comment_params)
      redirect_to "/posts/#{@comment.post_id}", notice: 'コメントを編集しました。'
    else
      redirect_to "/posts/#{@comment.post_id}/comments/#{@comment.id}/edit", alert: 'コメントの編集に失敗しました。'
    end
  end

  def destroy
    comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
    comment.destroy
    redirect_to "/posts/#{comment.post_id}", notice: '記事を削除しました。'
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
  
  def set_tag
    @tags = Tag.joins(:post_tags).group(:tag_id).order('count(post_id) desc')
  end

end

app/views/comments/_comment.html.haml
%article.Comment-box
  %header.Comment-box__header
    = link_to user_path(comment.user.id) do
      - if comment.user.icon?
        = image_tag comment.user.icon.url, class:"Comment-box__header__icon"
      - else
        = icon('fas', 'circle', class: "Comment-box__header__icon")
    .Comment-box__header__user
      .Comment-box__header__user__nickname
        = link_to user_path(comment.user.id) do
          = comment.user.nickname
      .Comment-box__header__user__id
        = link_to user_path(comment.user.id) do
          = comment.user.name
    .Comment-box__header__title
      = link_to post_path(comment.post.id) do
        @#{comment.post.title}
    .Comment-box__header__edit
      - if user_signed_in? && current_user.id == comment.user_id
        = link_to post_comment_path(comment.post.id, comment.id), method: :delete, data: { confirm: '削除しますか？' } do
          = icon('fas', 'trash',class: "Comment-box__header__edit__icon") 
        = link_to  edit_post_comment_path(comment.post.id, comment.id) do
          = icon('fas', 'ellipsis-v',class: "Comment-box__header__edit__icon") 
  .Comment-box__main
    %p.Comment-box__main__text
      = safe_join(comment.content.split("\n"),tag(:br))
    .Comment-box__main__date
      = comment.created_at.strftime("%Y/%m/%d %H:%M")
  .Comment-box__footer
    .Comment-box__footer__actions
      - if user_signed_in?
        .Comment-box__footer__actions__up
          - if current_user.already_comgood?(comment)
            = link_to "/posts/#{comment.post.id}/comments/#{comment.id}/comgoods/#{comment.comgoods.ids}", method: :delete do
              = icon('far', 'thumbs-up', class: "Comment-box__footer__actions__up__icon-on") 
          - else
            = link_to "/posts/#{comment.post.id}/comments/#{comment.id}/comgoods", method: :post do
              = icon('far', 'thumbs-up', class: "Comment-box__footer__actions__up__icon") 
          .Comment-box__footer__actions__up__count
            = comment.comgoods.count
        .Comment-box__footer__actions__down
          - if current_user.already_combad?(comment)
            = link_to "/posts/#{comment.post.id}/comments/#{comment.id}/combads/#{comment.comgoods.ids}", method: :delete do
              = icon('far', 'thumbs-down', class: "Comment-box__footer__actions__down__icon-on") 
          -else
            = link_to "/posts/#{comment.post.id}/comments/#{comment.id}/combads", method: :post do
              = icon('far', 'thumbs-down', class: "Comment-box__footer__actions__down__icon") 
          .Comment-box__footer__actions__down__count
            = comment.combads.count
      - else
        .Comment-box__footer__actions__up
          = icon('far', 'thumbs-up', class: "Comment-box__footer__actions__up__icon") 
          .Comment-box__footer__actions__up__count
            = comment.comgoods.count
        .Comment-box__footer__actions__down
          = icon('far', 'thumbs-down', class: "Comment-box__footer__actions__down__icon") 
          .Comment-box__footer__actions__down__count
            = comment.combads.count

app/views/comments/edit.html.haml
.wrapper
  = render "posts/top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          = render @post
          .Comments
            -# = icon('fas', 'reply', class: "Comments__icon")
            .Comments-list
              -# = render @comments
          - if user_signed_in?
            .Commentform-box
              .Commentform-box__header
                - if current_user.icon?
                  = image_tag current_user.icon.url, class:"Commentform-box__header__icon"
                - else
                  = icon('fas', 'circle', class: "Commentform-box__header__icon")
                .Commentform-box__header__user
                  .Commentform-box__header__user__nickname
                    = current_user.nickname
                  .Commentform-box__header__user__id
                    = current_user.name
                .Commentform-box__header__title
                  コメントを編集
              = form_with model:[@post, @comment], html: {class: "Form"}, local: true do |f|
                .Form__content
                  = f.text_area :content, class: 'Form__content__input' , placeholder: 'コメントを入力'
                .Form__submit
                  = f.submit '送信', class: 'Form__submit__btn'

      = render "posts/side_bar"