config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get '/post/tag/:name', to:"posts#tag"
  resources :users, only: [:edit, :update, :show] do
    get 'show_following'
    get 'show_follower'
    get 'show_article'
    get 'show_comment'
    get 'show_good'
    get 'show_question'
  end
  resources :relationships, only: [:create, :destroy]
  resources :posts do
    collection do
      get 'search'
    end
    resources :goods, only: [:create, :destroy]
    resources :bads, only: [:create, :destroy]
    resources :comments, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :comgoods, only: [:create, :destroy]
      resources :combads, only: [:create, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :good_users, through: :goods, source: :user
  has_many :bads, dependent: :destroy
  has_many :bad_users, through: :bads, source: :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :title, :content, presence: true
  self.inheritance_column = :_type_disabled
 
  def self.search(search)
    if search != ""
      if search == "質問"
        Post.where(type: 1)
      else
      Post.where('content LIKE(?) or title LIKE(?) or hashtag LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
      end
    else
      Post.all
    end
  end

  after_create do
    post = Post.find_by(id: id)
    tags = hashtag.to_s.gsub(/＃/, '#').scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |tag|
      hash = Tag.find_or_create_by(name: tag.downcase.delete('#'))
      post.tags << hash
    end
  end

  before_update do
    post = Post.find_by(id: id)
    post.tags.clear
    tags = hashtag.to_s.gsub(/＃/, '#').scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |tag|
      hash = Tag.find_or_create_by(name: tag.downcase.delete('#'))
      post.tags << hash
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  before_action :set_tag, only: [:index, :new, :create, :show, :edit, :update, :search, :tag]
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
    @post.post_tags.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path, notice: '記事を投稿しました。'
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path, notice: '記事を削除しました。'
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = @post.comments.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path, notice: '記事を更新しました'
    else
      render :edit
    end
  end

  def search
    @posts = Post.search(params[:keyword]).includes(:user).order("created_at DESC")
  end

  def tag
    @tag = Tag.find_by(name: params[:name])
    @posts = Post.where('hashtag LIKE(?)', "%#{@tag.name}%").includes(:user).order("created_at DESC")
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :type,:hashtag, hashtag_ids: []).merge(user_id: current_user.id)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end

  def set_tag
    @tags = Tag.joins(:post_tags).group(:tag_id).order('count(post_id) desc')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(hashtag)
    hashtag.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){ |word| link_to word, "/post/tag/#{word.delete("#")}",data: {"turbolinks" => false} }.html_safe
  end

end

app/views/posts/_comment_form.html.haml
.Commentform-box
  .Commentform-box__header
    - if current_user.icon?
      = image_tag current_user.icon.url, class:"Commentform-box__header__icon"
    -else
      = icon('fas', 'circle', class: "Commentform-box__header__icon")
    .Commentform-box__header__user
      .Commentform-box__header__user__nickname
        = current_user.nickname
      .Commentform-box__header__user__id
        = current_user.name
    .Commentform-box__header__title
  = form_with model:[@post, @comment], html: {class: "Form"}, local: true do |f|
    .Form__content
      = f.text_area :content, class: 'Form__content__input' , placeholder: 'コメントを入力'
    .Form__submit
      = f.submit '送信', class: 'Form__submit__btn'

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if post.errors.any?
    .Notification
      .alert
        %h2= "#{post.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - post.errors.full_messages.each do |message|
            %li= message
  %article.Post-box
    %header.Post-box__header
      .Post-box__header__top
        - if current_user.icon?
          = image_tag current_user.icon.url, class: "Post-box__header__top__icon"
        - else
          = icon('fas', 'circle', class: "Post-box__header__top__icon")
        .Post-box__header__top__user
          .Post-box__header__top__user__nickname
            = current_user.nickname
          .Post-box__header__top__user__id
            = current_user.name
        .Post-box__header__top__type-check
          = f.check_box :type
          = f.label :type, "質問"
        
      .Post-box__header__middle
        .Post-box__header__middle__title
          = f.text_field :title, autofocus: true, class: 'Post-box__header__middle__title-input' , placeholder: 'タイトルを入力'
    .Post-box__main
      = f.text_area :content, class: 'Post-box__main-input' , placeholder: '投稿内容を入力'
    .Post-box__footer
      .Post-box__footer__tags
        = f.text_field :hashtag, class:"Post-box__footer__tags__input",placeholder: 'タグを入力'
      .Post-box__footer__submit
        = f.submit '送信', class: 'Post-box__footer__submit__btn'

app/views/posts/_post.html.haml
%article.Post-box
  %header.Post-box__header
    .Post-box__header__top
      = link_to user_path(post.user.id) do
        - if post.user.icon?
          = image_tag post.user.icon.url, class:"Post-box__header__top__icon"
        - else
          = icon('fas', 'circle', class: "Post-box__header__top__icon")
      .Post-box__header__top__user
        .Post-box__header__top__user__nickname
          = link_to user_path(post.user.id) do
            = post.user.nickname
        .Post-box__header__top__user__id
          = link_to user_path(post.user.id) do
            = post.user.name
      .Post-box__header__top__type
        - if post.type == 1
          【質問】
      .Post-box__header__top__edit
        - if user_signed_in? && current_user.id == post.user_id
          = link_to  post_path(post.id), method: :delete, data: { confirm: '削除しますか？' } do
            = icon('fas', 'trash',class: "Post-box__header__top__edit__icon") 
          = link_to  edit_post_path(post.id) do
            = icon('fas', 'ellipsis-v',class: "Post-box__header__top__edit__icon") 
    .Post-box__header__middle
      .Post-box__header__middle__title
        = link_to  post_path(post.id) do
          = post.title
  .Post-box__main
    %p.Post-box__main__text
      = safe_join(post.content.split("\n"),tag(:br))
    .Post-box__main__date
      = post.created_at.strftime("%Y/%m/%d %H:%M")
  .Post-box__footer
    .Post-box__footer__tags
      - post.tags.each do|tag|
        .Post-box__footer__tags__tag
          = render_with_hashtags("#"+tag.name)
     
    .Post-box__footer__actions
      .Post-box__footer__actions__reply
        = link_to  post_path(post.id) do
          = icon('fas', 'reply',class: "Post-box__footer__actions__reply__icon") 
        .Post-box__footer__actions__reply__count
          = post.comments.count
      - if user_signed_in?
        .Post-box__footer__actions__up
          - if current_user.already_good?(post)
            = link_to "/posts/#{post.id}/goods/#{post.goods.ids}", method: :delete  do
              = icon('far', 'thumbs-up', class: "Post-box__footer__actions__up__icon-on") 
          - else
            = link_to post_goods_path(post.id), method: :post do
              = icon('far', 'thumbs-up', class: "Post-box__footer__actions__up__icon") 
          .Post-box__footer__actions__up__count
            = post.goods.count 
        .Post-box__footer__actions__down
          - if current_user.already_bad?(post)
            = link_to "/posts/#{post.id}/bads/#{post.bads.ids}", method: :delete  do
              = icon('far', 'thumbs-down', class: "Post-box__footer__actions__down__icon-on") 
          - else
            = link_to post_bads_path(post.id), method: :post do
              = icon('far', 'thumbs-down', class: "Post-box__footer__actions__down__icon") 
          .Post-box__footer__actions__down__count
            = post.bads.count
      - else
        .Post-box__footer__actions__up
          = icon('far', 'thumbs-up', class: "Post-box__footer__actions__down__icon") 
          .Post-box__footer__actions__up__count
            = post.goods.count
        .Post-box__footer__actions__down
          = icon('far', 'thumbs-down', class: "Post-box__footer__actions__down__icon") 
          .Post-box__footer__actions__down__count
            = post.bads.count

app/views/posts/_post_info.html.haml
%article.Post-box
  %header.Post-box__header
    .Post-box__header__top
      = icon('fas', 'circle', class: "Post-box__header__top__icon")
      .Post-box__header__top__user
        .Post-box__header__top__user__nickname
          info
        .Post-box__header__top__user__id
          info
      .Post-box__header__top__type
        index
      .Post-box__header__top__edit
    .Post-box__header__middle
      .Post-box__header__middle__title
        このアプリの使い方
  .Post-box__main
    %p.Post-box__main__text
      %b Step1 ユーザー登録 <br>
      ユーザー登録すると自分だけのページを作成できます。 <br><br>
      %b Step2 投稿 <br>
      右上の鉛筆ボタンから投稿できます。 <br>
      投稿には２種類『記事』と『質問』 <br>
      記事・・・自分の持っている情報をみんなと共有 <br>
      質問・・・自分の疑問を誰かにきいてみる <br><br>
      %b Step3 コメント <br>
      記事や質問にはコメントを返せます。 <br>
      記事の下のリプライボタンを押せばコメント投稿画面へ  <br><br>
      %b Step4 いいね <br>
      『記事』『質問』『コメント』には【いいね】が出来ます。<br>
      いいねは個人の評価に繋がりますので誰かの役に立つ投稿をしましょう。<br><br>
      %b Step5 フォロー <br>
      気になるユーザをフォローしましょう。 <br>
      フォローしたユーザーの投稿はタイムラインに表示されます。<br><br>
      %b Step6 検索 <br>
      検索には２種類あります。 <br>
      検索ボックス・・・キーワードを入力すると全投稿から該当記事を検索<br>
      ハッシュタグ・・・記事の投稿にはタグが付けられる。タグを押すと全投稿から該当タグを検索

    .Post-box__main__date
  .Post-box__footer
    .Post-box__footer__tags
    .Post-box__footer__actions
      .Post-box__footer__actions__reply
        = icon('fas', 'reply',class: "Post-box__footer__actions__reply__icon") 
        .Post-box__footer__actions__reply__count
          0
        .Post-box__footer__actions__up
          = icon('far', 'thumbs-up', class: "Post-box__footer__actions__down__icon") 
          .Post-box__footer__actions__up__count
            0
        .Post-box__footer__actions__down
          = icon('far', 'thumbs-down', class: "Post-box__footer__actions__down__icon") 
          .Post-box__footer__actions__down__count
            0

app/views/posts/_side_bar.html.haml
%nav.Side-items
  - if user_signed_in?
    .user
      = link_to user_path(current_user) do
        - if current_user.icon?
          = image_tag current_user.icon.url, class:"user__icon"
        - else
          = icon('fas', 'circle', class: "user__icon")
      .user__name
        = link_to user_path(current_user) do
          .user__name__nickname
            = current_user.nickname
        = link_to user_path(current_user) do
          .user__name__id
            = current_user.name
    %ul.posts
      投稿一覧
      - current_user.posts.reverse[0..4].each do |post|
        %li.posts__post
          = link_to  post_path(post.id) do
            - if post.type == 1
              【質問】
              = post.title
            - else
              = post.title
      
  %ul.tags
    タグ一覧
    - @tags.first(10).each do |tag|
      %li.tags__tag
        = render_with_hashtags("#"+tag.name)+"(#{tag.post_tags.count})"
  %footer
    %small.copyright
      @ 2020 shares.ninja

app/views/posts/_top_info.html.haml
%header.Top-info
  .Top-info__items
    .nav
      = link_to "/" do
        Shares

    .search-posts
      = form_with url: search_posts_path, local: true, class: "search-posts__input-box", method: :get do |f|
        = f.text_field :keyword, placeholder: "検索", class: "search-posts__input-box__text"
        = icon('fas', 'search', class: "search-posts__input-box__image")
        = f.submit "", class: "search-posts__input-box__btn"
        

  

    - if user_signed_in?
      .info
        .info__icons
          .info__icons__icon
            = link_to new_post_path do
              = icon('far', 'edit', class: "info__icons__icon-btn")
          .info__icons__icon
            = link_to user_path(current_user) do
              = icon('fas', 'home', class: "info__icons__icon-btn")
          .info__icons__icon
            = link_to edit_user_path(current_user) do
              - if current_user.icon?
                = image_tag current_user.icon.url, class:"info__icons__icon-btn"
              - else
                = icon('fas', 'circle', class: "info__icons__icon-btn")
    - else
      .submit
        = link_to new_user_registration_path do
          %input{type: "submit", value: "新規登録", class: "submit__new"}
        = link_to new_user_session_path do
          %input{type: "submit", value: "ログイン", class: "submit__login"}

app/views/posts/edit.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          %h1 投稿編集
          = render partial: 'form', locals: { post: @post }
          
      = render "side_bar"

app/views/posts/index.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          - if user_signed_in?
            - @posts = current_user.posts.includes(:user).order("created_at DESC")
            - current_user.followings.each do |user|
              - posts = user.posts.includes(:user).order("created_at DESC")
              - @posts += posts
              - @posts.sort_by! { |a| a[:created_at] }.reverse!
          - else
            = render "post_info"
          = render @posts
      = render "side_bar"

app/views/posts/new.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          %h1 新規投稿
          = render partial: 'form', locals: { post: @post }
          
      = render "side_bar"

app/views/posts/search.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          = render @posts
      = render "side_bar"

app/views/posts/show.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          = render @post
          - if @comments.present?
            .Comments
              = icon('fas', 'reply', class: "Comments__icon")
              .Comments-list
                = render @comments
          - if user_signed_in?
            =render "comment_form"

      = render "side_bar"

app/views/posts/tag.html.haml
.wrapper
  = render "top_info"
  .Body
    .Body__items 
      %main
        .Posts-list
          = render @posts
      = render "side_bar"